export class Client{
  id:number = 0;
  nombre:string = '';
  version_fox:string = '';
  imp_pdf:string = '';
  tipo:string = '';
  contacto:string = '';
  tecnico:string = '';
  servidor:boolean = false;
  servidor_windows:string = '';
  servidor_ip:string = '';
  servidor_contrasena:string = '';
  mail:boolean = false;
  mail_herramienta:string = '';
  mail_cuenta:string = '';
  mail_servidor:string = '';
  mail_contrasena:string = '';
  generacion_pdf:boolean = false;
  generacion_pdf_empresa:string = '';
  any_desk_id:string = '';
  any_desk_pass:string = '';
  recaudacion:string = '';
  logo:string = '';
}
